openapi: 3.0.1
info:
  title: KafkaTransport
  description: API Definition of KafkaTransport
  version: 1.0.0
servers:
- url: http://localhost:8290/publishMessages
paths:
  /:
    post:
      responses:
        default:
          description: Default response
